server:
  port: 5000

spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      ribbon:
        # Not needed since we excluded the dependency
        enabled: false
    # config consul discovery service
    consul:
      host: 192.168.167.114
      port: 8500
      enabled: true
      discovery:
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        preferIpAddress: true
        health-check-critical-timeout: 60s
        # Get only services that are passing the health check
        query-passing: true
    gateway:
      routes:
        - id: cdo-aas
          uri: lb://cdo-aas/
          predicates:
            - Path=/api/auth/**,/api/roles/**,/api/users/**
        - id: cdo-employee
          uri: lb://cdo-employees/
          predicates:
            - Path=/api/employees/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders:
              - "*"
            allowedMethods:
              - "GET"
              - "POST"
              - "OPTIONS"
              - "PATCH"
              - "PUT"
      default-filters:
        - name: Retry
          args:
            retries: 5
            methods: GET,POST,OPTIONS,PATCH,PUT
# Uncomment the configuration below if you want to enable route matching logs
#logging:
#  level:
#    org.springframework.cloud.gateway.handler.predicate: trace
