CREATE TABLE IF NOT EXISTS employees (
	`id` INTEGER AUTO_INCREMENT PRIMARY KEY,
	`username` VARCHAR(100) UNIQUE NOT NULL,
	`password` VARCHAR(100) NOT NULL,
	`fullname` VARCHAR(100) NOT NULL,
	`role` VARCHAR(100) NOT NULL
);